package com.twice.optipvp;

public enum LagSource {
    QUICK_CAMERA_MOVEMENT,
    ENTITY_RENDER_SPIKES,
    BUILD_RENDER_SPIKES,
    PARTICLE_OVERDRAW,
    SHADOW_UPDATES,
    CHUNK_REBUILD_BURSTS,
    BLOCK_ENTITY_TICK_SURGES,
    ITEM_ENTITY_STACKS,
    HOTBAR_ANIMATION_SPIKES,
    CHAT_OVERLAY_REFRESH,
    SCOREBOARD_REFRESH,
    CLOUD_RENDER,
    BIOME_BLEND,
    TRANSLUCENT_SORT,
    WATER_REFLECTION,
    LEAF_PARTICLES,
    NAMETAG_OVERDRAW,
    REDSTONE_TICK_BURSTS,
    EXP_ORB_FLOOD,
    WORLD_JOIN_STUTTER
}
